### ISSUE TITLE
Editing an coordinator-user trows exception 

### ISSUE THREAD

**Issue by isturm** [lecture2go/plugins-sdk-6.2#213]
MyL2go->Users

25.01.2016 14:01:40 org.apache.catalina.core.ApplicationDispatcher invoke
SCHWERWIEGEND: Servlet.service() for servlet lgadminusermanagement Servlet threw exception
java.lang.UnsupportedOperationException: Please make a copy of this read-only list before modifying it.
	at com.liferay.portal.kernel.util.UnmodifiableList.add(UnmodifiableList.java:46)
	at de.uhh.l2g.plugins.admin.AdminUserManagement.viewRole(AdminUserManagement.java:141)
	at sun.reflect.GeneratedMethodAccessor2943.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.liferay.portal.kernel.portlet.LiferayPortlet.callActionMethod(LiferayPortlet.java:148)
	at com.liferay.util.bridges.mvc.MVCPortlet.callActionMethod(MVCPortlet.java:247)
	at com.liferay.portal.kernel.portlet.LiferayPortlet.processAction(LiferayPortlet.java:78)
	at com.liferay.util.bridges.mvc.MVCPortlet.processAction(MVCPortlet.java:210)
	at com.liferay.portlet.FilterChainImpl.doFilter(FilterChainImpl.java:71)
	at com.liferay.portal.kernel.portlet.PortletFilterUtil.doFilter(PortletFilterUtil.java:48)
	at com.liferay.portal.kernel.servlet.PortletServlet.service(PortletServlet.java:112)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilterChain.doFilter(InvokerFilterChain.java:116)
	at com.liferay.portal.kernel.servlet.filters.invoker.InvokerFilter.doFilter(InvokerFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
	at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:749)
	at org.apache.catalina.core.ApplicationDispatcher.doInclude(ApplicationDispatcher.java:605)
	at org.apache.catalina.core.ApplicationDispatcher.include(ApplicationDispatcher.java:544)
	at com.liferay.portlet.InvokerPortletImpl.invoke(InvokerPortletImpl.java:583)
	at com.liferay.portlet.InvokerPortletImpl.invokeAction(InvokerPortletImpl.java:628)
	at com.liferay.portlet.InvokerPortletImpl.processAction(InvokerPortletImpl.java:308)
	at com.liferay.portlet.PortletContainerImpl._doProcessAction(PortletContainerImpl.java:402)
	at com.liferay.portlet.PortletContainerImpl.processAction(PortletContainerImpl.java:110)
	at com.liferay.portlet.SecurityPortletContainerWrapper.processAction(SecurityPortletContainerWrapper.java:109)
	at com.liferay.portlet.RestrictPortletContainerWrapper.processAction(RestrictPortletContainerWrapper.java:75)
	at com.liferay.portal.kernel.portlet.PortletContainerUtil.processAction(PortletContainerUtil.java:115)
	at com.liferay.portal.action.LayoutAction.processLayout(LayoutAction.java:378)
	at com.liferay.portal.action.LayoutAction.doExecute(LayoutAction.java:200)

**Comment by sgund** [comment]
Umodifyable List in Liferay occur... "Because you're retrieving a list of database entries. This list is unmodifiable because you cannot persist the list back to the database"

**Comment by sgund** [comment]
1) DB Table was inconsitent (Migrated Coordinator Data got lost somewhere and not all newly generated Liferay L2G Coordinators where added to coodinator table)

**Comment by sgund** [comment]
SELECT User_.userid, User_.screenName, User_.companyId, Users_Groups.groupId, Role_.name, Role_.RoleId, LG_Coordinator.institutionId, LG_Producer.institutionId FROM User_
JOIN Users_Roles ON User_.userId = Users_Roles.userId 
JOIN Role_ ON (Role_.roleId = Users_Roles.roleId)
JOIN Users_Groups ON (User_.userId = Users_Groups.userId)
LEFT JOIN LG_Coordinator ON (LG_Coordinator.coordinatorId = User_.userId AND Role_.name LIKE '%Coordinator%')
LEFT JOIN LG_Producer ON (LG_Producer.producerId = User_.userId AND Role_.name LIKE '%Producer%')
WHERE Role_.name LIKE '%L2Go%';

**Comment by sgund** [comment]
Part of the problem solved and commited

**Comment by sgund** [comment]
List works now, but there is an error on setting producer in some cases
